### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by dungtv543** [ncatlin/rgat#29]
I have a problem. I try with my x86 "hello world" application and it crashed (picture bellow).
![image](https://cloud.githubusercontent.com/assets/5428817/21921770/28cbf426-d99d-11e6-9a43-4c4a5347b4ed.png)

**Comment by ncatlin** [comment]
Could you share the binary or some information about it? (code, compiler) 
Thanks!

**Comment by dungtv543** [comment]
It is "Hello World" program, but i packed it by ASpack 2.4.

**Comment by ncatlin** [comment]
That is useful information, thank you! ASpack'ed binaries have some interesting behaviour and I'm working on reproducing and squashing any more crashes but the current version seems reasonably stable running them now.

**Comment by ncatlin** [comment]
ASPack traces fine with the re-write
